// examples/vue/src/App.vue
<script setup>
import { ref } from 'vue';

const editorConfig = {
  toolbar: {
    items: ['undo', 'redo', 'bold', 'italic', 'underline', 'bullet-list'],
  },
  theme: 'light',
  placeholder: 'Start typing...',
};

function handleReady(event) {
  const api = event.detail.api;
  api.setContent('<p>Hello Vue!</p>', 'html');
}

function handleContentChange(event) {
  console.log('Content changed:', event.detail.content);
}
</script>

<template>
  <div class="editor-container">
    <h1>Erix Editor + Vue</h1>
    <erix-editor :config="editorConfig" @erix-ready="handleReady" @erix-content-change="handleContentChange"></erix-editor>
  </div>
</template>

<style>
.editor-container {
  padding: 2rem;
  max-width: 800px;
  margin: 0 auto;
}
</style>

// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  standalone: false,
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'Erix Editor Angular Demo';
  charCount = 0;
  private editorApi: any = null;

  // Editor configuration
  editorConfig = {
    toolbar: {
      items: [
        'undo', 'redo',
        'bold', 'italic', 'underline', 'strikethrough',
        'bullet-list', 'ordered-list',
        'font-family', 'font-size'
      ]
    },
    theme: 'light',
    placeholder: 'Start typing your content here...'
  };

  onEditorReady(event: any) {
    this.editorApi = event.detail.api;
    console.log('Erix Editor is ready!', this.editorApi);
    
    // Set initial content
    this.editorApi.setContent('<p>Hello from <strong>Angular</strong>! 🎉</p>', 'html');
  }

  onContentChange(event: any) {
    const { content } = event.detail;
    this.charCount = content.text.length;
  }
}

<div class="editor-demo">
  <h1>Erix Editor - Angular Demo</h1>
  <p>Testing the Stencil web component integration with Angular 19</p>
  
  <div class="editor-container">
    <erix-editor 
      id="demo-editor"
      (erix-ready)="onEditorReady($event)"
      (erix-content-change)="onContentChange($event)">
    </erix-editor>
  </div>

  <div class="stats">
    <p>Character count: {{ charCount }}</p>
  </div>
</div>

<style>
  .editor-demo {
    max-width: 900px;
    margin: 2rem auto;
    padding: 1rem;
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }

  h1 {
    color: #333;
    margin-bottom: 0.5rem;
  }

  p {
    color: #666;
    margin-bottom: 1.5rem;
  }

  .editor-container {
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  }

  .stats {
    margin-top: 1rem;
    padding: 0.75rem;
    background: #f5f5f5;
    border-radius: 4px;
  }

  .stats p {
    margin: 0;
    font-size: 0.875rem;
    color: #555;
  }
</style>
